services:
    cosmo.peoplesign.captcha.peoplesign:
        class: cosmo\peoplesign\captcha\peoplesign
        calls:
            - [set_name, [cosmo.peoplesign.captcha.peoplesign]]
        arguments:
            - @dbal.conn
            - @cache
            - @config
            - @template
            - @user
            - @request
            - @log
        tags:
            - { name: captcha.plugins }